/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Giao_Dien;

import Entities.DocGia;
import java.awt.HeadlessException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.sql.*;
import javax.swing.JOptionPane;
//import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DELL
 */
public final class Doc_Gia extends javax.swing.JFrame {

    /**
     * Creates new form Doc_Gia
     */
    String Select_DocGia;
    public Doc_Gia() {
        initComponents();
        setLocationRelativeTo(null);

//        jButtonChinhSua.hide();
//        jButtonChinhSua.doClick();

    }
    public void ResetDocGia(){
        jTextMaDocGia.setText("");
        jTextHoTen.setText("");
        jTextSDT.setText("");
        long millis=System.currentTimeMillis();   
        java.sql.Date date=new java.sql.Date(millis);    
        jDateNgSinh.setDate(date);
        ComboBoxGioiTinh.setSelectedItem("Nam");
        jTextDiaChi.setText("");
        jTextEmail.setText("");
        ComboBoxVaiTro.setSelectedItem("Độc giả");
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButtonXacNhan = new javax.swing.JButton();
        jTextMaDocGia = new javax.swing.JTextField();
        jTextHoTen = new javax.swing.JTextField();
        jTextSDT = new javax.swing.JTextField();
        jTextDiaChi = new javax.swing.JTextField();
        jTextEmail = new javax.swing.JTextField();
        jDateNgSinh = new com.toedter.calendar.JDateChooser();
        jLabel9 = new javax.swing.JLabel();
        jButtonHuy = new javax.swing.JButton();
        jButtonChinhSua = new javax.swing.JButton();
        ComboBoxVaiTro = new javax.swing.JComboBox<>();
        ComboBoxGioiTinh = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Mã độc giả:");

        jLabel2.setText("Họ Tên:");

        jLabel3.setText("Giới tính:");

        jLabel4.setText("Ngày sinh:");

        jLabel5.setText("SĐT:");

        jLabel6.setText("Địa chỉ:");

        jLabel7.setText("Email:");

        jButtonXacNhan.setBackground(new java.awt.Color(0, 204, 255));
        jButtonXacNhan.setText("Xác nhận");
        jButtonXacNhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonXacNhanActionPerformed(evt);
            }
        });

        jTextMaDocGia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextMaDocGiaActionPerformed(evt);
            }
        });

        jTextDiaChi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextDiaChiActionPerformed(evt);
            }
        });

        jTextEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextEmailActionPerformed(evt);
            }
        });

        jDateNgSinh.setDateFormatString("dd/MM/yyyy");
        jDateNgSinh.setDoubleBuffered(false);
        jDateNgSinh.setMaxSelectableDate(new java.util.Date(253370743298000L));
        jDateNgSinh.setMinSelectableDate(new java.util.Date(-62135791102000L));

        jLabel9.setText("Vai trò");

        jButtonHuy.setBackground(new java.awt.Color(0, 204, 255));
        jButtonHuy.setText("Huỷ");
        jButtonHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHuyActionPerformed(evt);
            }
        });

        jButtonChinhSua.setBackground(new java.awt.Color(0, 204, 255));
        jButtonChinhSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imges/icons8_edit_23px.png"))); // NOI18N
        jButtonChinhSua.setText("Chỉnh sửa");
        jButtonChinhSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonChinhSuaActionPerformed(evt);
            }
        });

        ComboBoxVaiTro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Độc giả", "Thủ thư" }));

        ComboBoxGioiTinh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam", "Nữ" }));

        jPanel1.setBackground(new java.awt.Color(0, 204, 255));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imges/icons8_more_info_35px.png"))); // NOI18N
        jLabel8.setText("Thông Tin Độc Giả");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonXacNhan)
                .addGap(50, 50, 50)
                .addComponent(jButtonHuy)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(139, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonChinhSua)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextMaDocGia)
                            .addComponent(jTextHoTen)
                            .addComponent(jTextSDT)
                            .addComponent(jTextDiaChi)
                            .addComponent(jTextEmail)
                            .addComponent(jDateNgSinh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ComboBoxVaiTro, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ComboBoxGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 140, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jButtonChinhSua)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextMaDocGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ComboBoxGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDateNgSinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextSDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ComboBoxVaiTro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonXacNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonHuy, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextMaDocGiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextMaDocGiaActionPerformed

    }//GEN-LAST:event_jTextMaDocGiaActionPerformed

    private void jTextDiaChiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextDiaChiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextDiaChiActionPerformed

    private void jTextEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextEmailActionPerformed

    private void jButtonXacNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonXacNhanActionPerformed

       //jTextMaDocGia.setText(Select_DocGia);
        KetNoiCSDL KN = new KetNoiCSDL();
        DocGia DG = new DocGia();
//      Man_Hinh_Chinh MHC = new Man_Hinh_Chinh();
        DG.setMaDocGia(jTextMaDocGia.getText());
        DG.setHoTen(jTextHoTen.getText());
        
        String GT = (String) ComboBoxGioiTinh.getSelectedItem();
        DG.setGioiTinh(GT);
 //     System.out.println(DG.getGioiTinh());
        
        DG.setNgSinh(jDateNgSinh.getDate());
        Date date = DG.getNgSinh();
        DateFormat dateFormat = null;
        dateFormat = new SimpleDateFormat("dd/MM/yyyy");
 //          System.out.println("dd/MM/yyyy: " + dateFormat.format(date));
        String NgS = dateFormat.format(date);
        
        DG.setSDT(jTextSDT.getText());
        DG.setDiaChi(jTextDiaChi.getText());
        DG.setEmail(jTextEmail.getText());
        
        String VT = (String) ComboBoxVaiTro.getSelectedItem();
        DG.setVaiTro(VT);
        if(Select_DocGia == null){
            try{
//                String URL;
//                URL = "jdbc:oracle:thin:@localhost:1522:NQL";
//                String username = "QUOCLUU";
//                String password = "abc";
                Connection conn = DriverManager.getConnection(KN.URL ,KN.username, KN.password);
                String sql = "INSERT INTO DOCGIA (MADOCGIA,HOTEN,GIOITINH,NGSINH,SDT,DIACHI,EMAIL,VAITRO) "
                        + "VALUES(?,?,?,TO_DATE(?,'DD/MM/YYYY'),?,?,?,?)";
                PreparedStatement ps = conn.prepareStatement(sql);
                ps.setString(1, DG.getMaDocGia());
                ps.setString(2, DG.getHoTen());
                ps.setString(3, DG.getGioiTinh());
                ps.setString(4, NgS);
                ps.setString(5, DG.getSDT());
                ps.setString(6, DG.getDiaChi());
                ps.setString(7, DG.getEmail());
                ps.setString(8, DG.getVaiTro());
//                DefaultTableModel model = (DefaultTableModel) MHC.jTableDocGia.getModel();
                ResultSet rs = ps.executeQuery();
                if(rs.next()){
                    JOptionPane.showMessageDialog(this, "Thêm độc giả thành công!");
                    ResetDocGia();
//                    this.dispose();
                }
                else{
                    JOptionPane.showMessageDialog(this, "Thêm độc giả thất bại!");
                }
                ps.close();
                conn.close();
            }catch(HeadlessException | SQLException ex){
                System.out.println(ex);
            }
        }
        else{
            try{
//                String URL;
//                URL = "jdbc:oracle:thin:@localhost:1522:NQL";
//                String username = "QUOCLUU";
//                String password = "abc";
                Connection conn = DriverManager.getConnection(KN.URL ,KN.username, KN.password);
                String sql = "UPDATE DOCGIA SET HOTEN = ?, GIOITINH = ?," +
                                                "NGSINH = TO_DATE(?,'DD/MM/YYYY'),SDT = ?,DIACHI = ?," +
                                                "EMAIL = ?, VAITRO = ?" +
                                    "WHERE MADOCGIA = ?";
                PreparedStatement ps = conn.prepareStatement(sql);
                //ps.setString(8, DG.getMaDocGia());
                ps.setString(8, Select_DocGia);
                
                ps.setString(1, DG.getHoTen());
                ps.setString(2, DG.getGioiTinh());
                ps.setString(3, NgS);
                ps.setString(4, DG.getSDT());
                ps.setString(5, DG.getDiaChi());
                ps.setString(6, DG.getEmail());
                ps.setString(7, DG.getVaiTro());
//                DefaultTableModel model = (DefaultTableModel) MHC.jTableDocGia.getModel();
                ResultSet rs = ps.executeQuery();
                if(rs.next()){
                    JOptionPane.showMessageDialog(this, "Cập nhật độc giả thành công!");
                    this.dispose();
                }
                else{
                    JOptionPane.showMessageDialog(this, "Cập nhật độc giả thất bại!");
                }
                ps.close();
                conn.close();
            }catch(HeadlessException | SQLException ex){
                JOptionPane.showMessageDialog(this,ex);
            }
        }
      
    }//GEN-LAST:event_jButtonXacNhanActionPerformed

    private void jButtonHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHuyActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonHuyActionPerformed

    private void jButtonChinhSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonChinhSuaActionPerformed
        KetNoiCSDL KN = new KetNoiCSDL();
        if(Select_DocGia != null){
            try{
//                String URL;
//                URL = "jdbc:oracle:thin:@localhost:1522:NQL";
//                String username = "QUOCLUU";
//                String password = "abc";
                Connection conn = DriverManager.getConnection(KN.URL ,KN.username, KN.password);
                String sql = "SELECT * FROM DocGia\n" +
                             "WHERE MaDocGia=?";
                PreparedStatement ps = conn.prepareStatement(sql);
                ps.setString(1, Select_DocGia);
                ResultSet rs = ps.executeQuery();
                if(rs.next()){
                    jTextMaDocGia.setText(rs.getString("MaDocGia"));
                    jTextHoTen.setText(rs.getString("HoTen"));
                    jTextSDT.setText(rs.getString("SDT"));
                    jDateNgSinh.setDate(rs.getDate("NgSinh"));
                    ComboBoxGioiTinh.setSelectedItem(rs.getString("GioiTinh"));
                    jTextDiaChi.setText(rs.getString("DiaChi"));
                    jTextEmail.setText(rs.getString("Email"));
                    ComboBoxVaiTro.setSelectedItem(rs.getString("VaiTro"));
                }
                else{
                    JOptionPane.showMessageDialog(this, "Lỗi xác thực!");
                }
                ps.close();
                conn.close();
            }catch(HeadlessException | SQLException ex){
                System.out.println(ex);
            }
            jTextMaDocGia.disable();
        }
        else{
            jButtonChinhSua.hide();
        }
    }//GEN-LAST:event_jButtonChinhSuaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Doc_Gia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Doc_Gia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Doc_Gia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Doc_Gia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Doc_Gia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboBoxGioiTinh;
    private javax.swing.JComboBox<String> ComboBoxVaiTro;
    private javax.swing.JButton jButtonChinhSua;
    private javax.swing.JButton jButtonHuy;
    private javax.swing.JButton jButtonXacNhan;
    private com.toedter.calendar.JDateChooser jDateNgSinh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextDiaChi;
    private javax.swing.JTextField jTextEmail;
    private javax.swing.JTextField jTextHoTen;
    private javax.swing.JTextField jTextMaDocGia;
    private javax.swing.JTextField jTextSDT;
    // End of variables declaration//GEN-END:variables


}
