/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Giao_Dien;

import Entities.PhieuTra;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author DELL
 */
public class Form_ThongTinPhieuTra extends javax.swing.JFrame {

    /**
     * Creates new form Form_ThongTinPhieuTra
     */
    String Select_PhieuTra;
    public Form_ThongTinPhieuTra() {
        initComponents();
        setLocationRelativeTo(null);
    }
    public void ResetPhieuTra(){
        jTextMaPhieuTra.setText("");
        jTextMaPhieuMuon.setText("");
        jTextMaDocGia.setText("");
        jTextMaSach.setText("");
        long millis=System.currentTimeMillis();   
        java.sql.Date date=new java.sql.Date(millis);    
        jDateNgayTraSach.setDate(date);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextMaPhieuTra = new javax.swing.JTextField();
        jTextMaPhieuMuon = new javax.swing.JTextField();
        jTextMaDocGia = new javax.swing.JTextField();
        jTextMaSach = new javax.swing.JTextField();
        jDateNgayTraSach = new com.toedter.calendar.JDateChooser();
        jButtonXacNhan = new javax.swing.JButton();
        jButtonHuy = new javax.swing.JButton();
        jButtonChinhSua = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Thông tin phiếu trả sách - Quản lý thư viện");
        setPreferredSize(new java.awt.Dimension(521, 534));

        jLabel1.setText("Mã phiếu trả:");
        jLabel1.setPreferredSize(new java.awt.Dimension(47, 16));

        jLabel2.setText("Mã phiếu mượn:");
        jLabel2.setPreferredSize(new java.awt.Dimension(47, 16));

        jLabel3.setText("Mã độc giả:");
        jLabel3.setPreferredSize(new java.awt.Dimension(47, 16));

        jLabel4.setText("Mã sách");
        jLabel4.setPreferredSize(new java.awt.Dimension(47, 16));

        jLabel6.setText("Ngày trả sách");
        jLabel6.setPreferredSize(new java.awt.Dimension(47, 16));

        jTextMaSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextMaSachActionPerformed(evt);
            }
        });

        jDateNgayTraSach.setDateFormatString("dd/MM/yyyy");

        jButtonXacNhan.setBackground(new java.awt.Color(0, 204, 255));
        jButtonXacNhan.setText("Xác nhận");
        jButtonXacNhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonXacNhanActionPerformed(evt);
            }
        });

        jButtonHuy.setBackground(new java.awt.Color(0, 204, 255));
        jButtonHuy.setText("Huỷ");
        jButtonHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHuyActionPerformed(evt);
            }
        });

        jButtonChinhSua.setBackground(new java.awt.Color(0, 204, 255));
        jButtonChinhSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imges/icons8_edit_23px.png"))); // NOI18N
        jButtonChinhSua.setText("Chỉnh sửa");
        jButtonChinhSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonChinhSuaActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 204, 255));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imges/icons8_view_details_35px.png"))); // NOI18N
        jLabel5.setText("Thông tin phiếu trả sách");
        jLabel5.setPreferredSize(new java.awt.Dimension(176, 27));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(139, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(100, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jButtonChinhSua)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(27, 27, 27)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTextMaSach, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                                .addComponent(jTextMaDocGia, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                                .addComponent(jTextMaPhieuMuon, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                                .addComponent(jDateNgayTraSach, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextMaPhieuTra))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonXacNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonHuy, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonChinhSua)
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextMaPhieuTra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextMaPhieuMuon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextMaDocGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextMaSach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDateNgayTraSach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonHuy, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonXacNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(61, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextMaSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextMaSachActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextMaSachActionPerformed

    private void jButtonHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHuyActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonHuyActionPerformed

    private void jButtonXacNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonXacNhanActionPerformed
        KetNoiCSDL KN = new KetNoiCSDL();
        PhieuTra PT = new PhieuTra();
        PT.setMaPhieuTra(jTextMaPhieuTra.getText());
        PT.setMaPhieuMuon(jTextMaPhieuMuon.getText());
        PT.setMaDocGia(jTextMaDocGia.getText());
        PT.setMaSach(jTextMaSach.getText());
        
        PT.setNgayTraSach(jDateNgayTraSach.getDate());
        Date date = PT.getNgayTraSach();
        DateFormat dateFormat = null;
        dateFormat = new SimpleDateFormat("dd/MM/yyyy");
        String NgayTrS = dateFormat.format(date);
        
        if(Select_PhieuTra == null){
            try{
//                String URL;
//                URL = "jdbc:oracle:thin:@localhost:1522:NQL";
//                String username = "QUOCLUU";
//                String password = "abc";
                Connection conn = DriverManager.getConnection(KN.URL ,KN.username, KN.password);
                String sql = "INSERT INTO PHIEUTRASACH (MaPhieuTra, MaPhieuMuon, MaDocGia, MaSach, NgayTraSach) \n" +
                                                "VALUES (?,?,?,?,TO_DATE(?,'DD/MM/YYYY'))";
                PreparedStatement ps = conn.prepareStatement(sql);
                ps.setString(1, PT.getMaPhieuTra());
                ps.setString(2, PT.getMaPhieuMuon());
                ps.setString(3, PT.getMaDocGia());
                ps.setString(4, PT.getMaSach());
                ps.setString(5, NgayTrS);
                ResultSet rs = ps.executeQuery();
                if(rs.next()){
                    JOptionPane.showMessageDialog(this, "Thêm phiếu trả thành công!");
                    ResetPhieuTra();
//                    this.dispose();
                }
                else{
                    JOptionPane.showMessageDialog(this, "Thêm phiếu trả thất bại!");
                }
                ps.close();
                conn.close();
            }catch(HeadlessException | SQLException ex){
                JOptionPane.showMessageDialog(this,ex);
            }
        }
        else{
            try{
//                String URL;
//                URL = "jdbc:oracle:thin:@localhost:1522:NQL";
//                String username = "QUOCLUU";
//                String password = "abc";
                Connection conn = DriverManager.getConnection(KN.URL ,KN.username, KN.password);
                String sql = "UPDATE PHIEUTRASACH SET MaPhieuMuon = ?, MaDocGia = ?, MaSach = ?," +
                                            "NgayTraSach = TO_DATE(?,'DD/MM/YYYY')"+
                                    "WHERE MaPhieuTra = ?";
                PreparedStatement ps = conn.prepareStatement(sql);
                ps.setString(5, Select_PhieuTra);
                
                ps.setString(1, PT.getMaPhieuMuon());
                ps.setString(2, PT.getMaDocGia());
                ps.setString(3, PT.getMaSach());
                ps.setString(4, NgayTrS);
                
                ResultSet rs = ps.executeQuery();
                if(rs.next()){
                    JOptionPane.showMessageDialog(this, "Cập nhật phiếu trả thành công!");
                    this.dispose();
                }
                else{
                    JOptionPane.showMessageDialog(this, "Cập nhật phiếu trả thất bại!");
                }
                ps.close();
                conn.close();
            }catch(HeadlessException | SQLException ex){
                JOptionPane.showMessageDialog(this,ex);
            }
        }

    }//GEN-LAST:event_jButtonXacNhanActionPerformed

    private void jButtonChinhSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonChinhSuaActionPerformed
        KetNoiCSDL KN = new KetNoiCSDL();
        if(Select_PhieuTra != null){
            try{
//                String URL;
//                URL = "jdbc:oracle:thin:@localhost:1522:NQL";
//                String username = "QUOCLUU";
//                String password = "abc";
                Connection conn = DriverManager.getConnection(KN.URL ,KN.username, KN.password);
                String sql = "SELECT * FROM PhieuTraSach\n" +
                             "WHERE MaPhieuTra=?";
                PreparedStatement ps = conn.prepareStatement(sql);
                ps.setString(1, Select_PhieuTra);
                ResultSet rs = ps.executeQuery();
                if(rs.next()){
                    jTextMaPhieuTra.setText(rs.getString("MaPhieuTra"));
                    jTextMaPhieuMuon.setText(rs.getString("MaPhieuMuon"));
                    jTextMaDocGia.setText(rs.getString("MaDocGia"));
                    jTextMaSach.setText(rs.getString("MaSach"));
                    jDateNgayTraSach.setDate(rs.getDate("NgayTraSach"));
                }
                else{
                    JOptionPane.showMessageDialog(this, "Lỗi xác thực!");
                }
                ps.close();
                conn.close();
            }catch(HeadlessException | SQLException ex){
                System.out.println(ex);
            }
            jTextMaPhieuTra.disable();
        }
        else{
            jButtonChinhSua.hide();
        }
    }//GEN-LAST:event_jButtonChinhSuaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_ThongTinPhieuTra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_ThongTinPhieuTra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_ThongTinPhieuTra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_ThongTinPhieuTra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_ThongTinPhieuTra().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonChinhSua;
    private javax.swing.JButton jButtonHuy;
    private javax.swing.JButton jButtonXacNhan;
    private com.toedter.calendar.JDateChooser jDateNgayTraSach;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextMaDocGia;
    private javax.swing.JTextField jTextMaPhieuMuon;
    private javax.swing.JTextField jTextMaPhieuTra;
    private javax.swing.JTextField jTextMaSach;
    // End of variables declaration//GEN-END:variables
}
