/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Giao_Dien;

import Entities.PhieuMuon;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import java.sql.CallableStatement;


/**
 *s
 * @author DELL
 */
public class Form_ThongTinPhieuMuon extends javax.swing.JFrame {

    /**
     * Creates new form Form_ThongTinPhieuMuon
     */
    String Select_PhieuMuon;
    public Form_ThongTinPhieuMuon() {
        initComponents();
        setLocationRelativeTo(null);
    }
    public void ResetPhieuMuon(){
        jTextMaPhieuMuon.setText("");
        jTextMaDocGia.setText("");
        jTextMaSach.setText("");
        long millis=System.currentTimeMillis();   
        java.sql.Date date=new java.sql.Date(millis);    
        jDateNgayMuonSach.setDate(date);
        jComboBoxTinhTrangPM.setSelectedItem("Đang mượn");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextMaPhieuMuon = new javax.swing.JTextField();
        jTextMaDocGia = new javax.swing.JTextField();
        jTextMaSach = new javax.swing.JTextField();
        jDateNgayMuonSach = new com.toedter.calendar.JDateChooser();
        jComboBoxTinhTrangPM = new javax.swing.JComboBox<>();
        jButtonXacNhan = new javax.swing.JButton();
        jButtonHuy = new javax.swing.JButton();
        jButtonChinhSua = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Thông tin phiếu mượn sách - Quản lý thư viện");

        jLabel1.setText("Mã phiếu mượn:");
        jLabel1.setPreferredSize(new java.awt.Dimension(47, 16));

        jLabel2.setText("Mã độc giả");
        jLabel2.setPreferredSize(new java.awt.Dimension(47, 16));

        jLabel3.setText("Mã sách:");

        jLabel4.setText("Ngày mượn sách:");
        jLabel4.setPreferredSize(new java.awt.Dimension(47, 16));

        jLabel5.setText("Tình trạng phiếu mượn:");
        jLabel5.setPreferredSize(new java.awt.Dimension(47, 16));

        jTextMaPhieuMuon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextMaPhieuMuonActionPerformed(evt);
            }
        });

        jDateNgayMuonSach.setDateFormatString("dd/MM/yyyy");

        jComboBoxTinhTrangPM.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Đang mượn", "Đã trả" }));

        jButtonXacNhan.setBackground(new java.awt.Color(0, 204, 255));
        jButtonXacNhan.setText("Xác nhận");
        jButtonXacNhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonXacNhanActionPerformed(evt);
            }
        });

        jButtonHuy.setBackground(new java.awt.Color(0, 204, 255));
        jButtonHuy.setText("Huỷ");
        jButtonHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHuyActionPerformed(evt);
            }
        });

        jButtonChinhSua.setBackground(new java.awt.Color(0, 204, 255));
        jButtonChinhSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imges/icons8_edit_23px.png"))); // NOI18N
        jButtonChinhSua.setText("Chỉnh sửa");
        jButtonChinhSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonChinhSuaActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 204, 255));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imges/icons8_view_details_35px_3.png"))); // NOI18N
        jLabel6.setText("Thông tin phiếu mượn sách");
        jLabel6.setPreferredSize(new java.awt.Dimension(176, 27));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(105, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(106, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonChinhSua)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextMaSach, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                            .addComponent(jTextMaDocGia, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                            .addComponent(jDateNgayMuonSach, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBoxTinhTrangPM, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextMaPhieuMuon))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonXacNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73)
                .addComponent(jButtonHuy, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jButtonChinhSua)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextMaPhieuMuon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextMaDocGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextMaSach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jDateNgayMuonSach, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxTinhTrangPM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonXacNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonHuy, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextMaPhieuMuonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextMaPhieuMuonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextMaPhieuMuonActionPerformed

    private void jButtonHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHuyActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonHuyActionPerformed

    private void jButtonXacNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonXacNhanActionPerformed
        KetNoiCSDL KN = new KetNoiCSDL();
        PhieuMuon PM = new PhieuMuon();
//      Man_Hinh_Chinh MHC = new Man_Hinh_Chinh();
        PM.setMaPhieuMuon(jTextMaPhieuMuon.getText());
        PM.setMaDocGia(jTextMaDocGia.getText());
        PM.setMaSach(jTextMaSach.getText());
        
        PM.setNgayMuonSach(jDateNgayMuonSach.getDate());
        Date date = PM.getNgayMuonSach();
        DateFormat dateFormat = null;
        dateFormat = new SimpleDateFormat("dd/MM/yyyy");
        String NgayMS = dateFormat.format(date);
        
        String TTPM = (String) jComboBoxTinhTrangPM.getSelectedItem();
        PM.setTinhTrangPM(TTPM);
        
        if(Select_PhieuMuon == null){
            try{
//                String URL;
//                URL = "jdbc:oracle:thin:@localhost:1522:NQL";
//                String username = "QUOCLUU";
//                String password = "abc";
                Connection conn = DriverManager.getConnection(KN.URL ,KN.username, KN.password);
//                String sql = "INSERT INTO PHIEUMUONSACH (MaPhieuMuon, MaDocGia, MaSach, NgayMuonSach, TinhTrangPM) \n" +
//                                                "VALUES (?,?,?,TO_DATE(?,'DD/MM/YYYY'),?)";
                String sql = "{CALL INSERT_PHIEUMUON(?,?,?,TO_DATE(?,'DD/MM/YYYY'),?)}";
                CallableStatement ps = conn.prepareCall(sql);
                //PreparedStatement ps = conn.prepareStatement(sql);
                ps.setString(1, PM.getMaPhieuMuon());
                ps.setString(2, PM.getMaDocGia());
                ps.setString(3, PM.getMaSach());
                ps.setString(4, NgayMS);
                ps.setString(5, PM.getTinhTrangPM());
                ResultSet rs = ps.executeQuery();
                if(rs.next()){
                    JOptionPane.showMessageDialog(this, "Thêm phiếu mượn thành công!");
                    ResetPhieuMuon();
//                    this.dispose();
                }
                else{
                    JOptionPane.showMessageDialog(this, "Thêm phiếu mượn thất bại!");
                }
                ps.close();
                conn.close();
            }catch(HeadlessException | SQLException ex){
                JOptionPane.showMessageDialog(this, "Thêm phiếu mượn thất bại!");
            }
        }
        else{
            try{
//                String URL;
//                URL = "jdbc:oracle:thin:@localhost:1522:NQL";
//                String username = "QUOCLUU";
//                String password = "abc";
                Connection conn = DriverManager.getConnection(KN.URL ,KN.username, KN.password);
                String sql = "UPDATE PHIEUMUONSACH SET MaDocGia = ?, MaSach = ?," +
                                            "NgayMuonSach = TO_DATE(?,'DD/MM/YYYY'),TinhTrangPM = ?"+
                                    "WHERE MaPhieuMuon = ?";
                PreparedStatement ps = conn.prepareStatement(sql);
                ps.setString(5, Select_PhieuMuon);
                
                ps.setString(1, PM.getMaDocGia());
                ps.setString(2, PM.getMaSach());
                ps.setString(3, NgayMS);
                ps.setString(4, PM.getTinhTrangPM());
                
                ResultSet rs = ps.executeQuery();
                if(rs.next()){
                    JOptionPane.showMessageDialog(this, "Cập nhật phiếu mượn thành công!");
                    this.dispose();
                }
                else{
                    JOptionPane.showMessageDialog(this, "Cập nhật phiếu mượn thất bại!");
                }
                ps.close();
                conn.close();
            }catch(HeadlessException | SQLException ex){
                JOptionPane.showMessageDialog(this,ex);
            }
        }
        
    }//GEN-LAST:event_jButtonXacNhanActionPerformed

    private void jButtonChinhSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonChinhSuaActionPerformed
        KetNoiCSDL KN = new KetNoiCSDL();
        if(Select_PhieuMuon != null){
            try{
//                String URL;
//                URL = "jdbc:oracle:thin:@localhost:1522:NQL";
//                String username = "QUOCLUU";
//                String password = "abc";
                Connection conn = DriverManager.getConnection(KN.URL ,KN.username, KN.password);
                String sql = "SELECT * FROM PhieuMuonSach\n" +
                             "WHERE MaPhieuMuon=?";
                PreparedStatement ps = conn.prepareStatement(sql);
                ps.setString(1, Select_PhieuMuon);
                ResultSet rs = ps.executeQuery();
                if(rs.next()){
                    jTextMaPhieuMuon.setText(rs.getString("MaPhieuMuon"));
                    jTextMaDocGia.setText(rs.getString("MaDocGia"));
                    jTextMaSach.setText(rs.getString("MaSach"));
                    jDateNgayMuonSach.setDate(rs.getDate("NgayMuonSach"));
                    jComboBoxTinhTrangPM.setSelectedItem(rs.getString("TinhTrangPM"));
                }
                else{
                    JOptionPane.showMessageDialog(this, "Lỗi xác thực!");
                }
                ps.close();
                conn.close();
            }catch(HeadlessException | SQLException ex){
                System.out.println(ex);
            }
            jTextMaPhieuMuon.disable();
        }
        else{
            jButtonChinhSua.hide();
        }
    }//GEN-LAST:event_jButtonChinhSuaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_ThongTinPhieuMuon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_ThongTinPhieuMuon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_ThongTinPhieuMuon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_ThongTinPhieuMuon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_ThongTinPhieuMuon().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonChinhSua;
    private javax.swing.JButton jButtonHuy;
    private javax.swing.JButton jButtonXacNhan;
    private javax.swing.JComboBox<String> jComboBoxTinhTrangPM;
    private com.toedter.calendar.JDateChooser jDateNgayMuonSach;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextMaDocGia;
    private javax.swing.JTextField jTextMaPhieuMuon;
    private javax.swing.JTextField jTextMaSach;
    // End of variables declaration//GEN-END:variables
}
